/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmaCoMgr;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Network.CityNetwork;
import Business.Network.Network;
import Business.Network.StateNetwork;
import Business.Organization.FDAMgrOrganization;
import Business.Organization.Organization;
import Business.Start.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.PC_FdaWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chirag
 */
public class AddDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrugJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    Ecosystem ecosystem;

    public AddDrugJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        populateDrugTable();
        populateReqTable();

        popDrugType();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        mednamejTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        compoundsjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        additivesjTextField = new javax.swing.JTextField();
        expdatejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sendjButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reqjTable = new javax.swing.JTable();
        backButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dcjTextField = new javax.swing.JTextField();
        dajTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sideeffectsTextField1 = new javax.swing.JTextField();
        drugtypejComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gnamejTextField1 = new javax.swing.JTextField();

        jLabel1.setText("Add new Drug");

        drugjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Number", "Drug Type", "Medicine Name", "Compounds", "Additives", "Dosage", "Side effects", "Expiry Date", "Approval Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(drugjTable);
        if (drugjTable.getColumnModel().getColumnCount() > 0) {
            drugjTable.getColumnModel().getColumn(0).setResizable(false);
            drugjTable.getColumnModel().getColumn(1).setResizable(false);
            drugjTable.getColumnModel().getColumn(2).setResizable(false);
            drugjTable.getColumnModel().getColumn(3).setResizable(false);
            drugjTable.getColumnModel().getColumn(4).setResizable(false);
            drugjTable.getColumnModel().getColumn(5).setResizable(false);
            drugjTable.getColumnModel().getColumn(6).setResizable(false);
            drugjTable.getColumnModel().getColumn(7).setResizable(false);
            drugjTable.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel2.setText("Medicine Name:");

        jLabel3.setText("Compounds:");

        jLabel4.setText("Additives:");

        jLabel5.setText("Expiry Date:");

        jButton1.setText("Create new drug");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sendjButton2.setText("Send for approval");
        sendjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButton2ActionPerformed(evt);
            }
        });

        reqjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Drug Name", "Sender Co", "Sender", "Time Sent", "Approved/Rejected By", "Status", "Time Resolved"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reqjTable);
        if (reqjTable.getColumnModel().getColumnCount() > 0) {
            reqjTable.getColumnModel().getColumn(0).setResizable(false);
            reqjTable.getColumnModel().getColumn(1).setResizable(false);
            reqjTable.getColumnModel().getColumn(2).setResizable(false);
            reqjTable.getColumnModel().getColumn(3).setResizable(false);
            reqjTable.getColumnModel().getColumn(4).setResizable(false);
            reqjTable.getColumnModel().getColumn(5).setResizable(false);
            reqjTable.getColumnModel().getColumn(6).setResizable(false);
        }

        backButton2.setText("<<Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Dosage for Children: ");

        jLabel7.setText("Dosage for Adults:");

        jLabel8.setText("Side effects:");

        drugtypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Drug type");

        jLabel10.setText("Generic Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sideeffectsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(additivesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(sendjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(backButton2)
                                        .addGap(170, 170, 170))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(drugtypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(dajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(14, 14, 14))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(compoundsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(14, 14, 14)
                                                        .addComponent(jLabel5)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(expdatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(mednamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(gnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(620, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mednamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(gnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(additivesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(expdatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(compoundsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(dcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sideeffectsTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugtypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(sendjButton2)
                    .addComponent(backButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mname = mednamejTextField1.getText();
       if(Pattern.matches("[a-zA-Z]+", mname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Medicine Name", null, JOptionPane.CANCEL_OPTION);
      return;
       } 
       
       String coname = compoundsjTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", coname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Compound Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       String addname = additivesjTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", addname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Additives Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       String sidname = sideeffectsTextField1.getText();
       if(Pattern.matches("[a-zA-Z]+", sidname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Side Effect Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       
        Drug d = new Drug();
        d.setMedicineName(mednamejTextField1.getText());
        d.setCompoundName(compoundsjTextField.getText());
        d.setAdditives(additivesjTextField.getText());
        d.setExpDate(expdatejTextField.getText());
        d.setManufacturer(enterprise.getName());
        d.setDosage("Children: " + dcjTextField.getText() + "\n" + "Adults:" + dajTextField1.getText());
        d.setSide_effects(sideeffectsTextField1.getText());
        d.setDrugType((Drug.DrugType) drugtypejComboBox.getSelectedItem());
        d.setGenericName(gnamejTextField1.getText());
        if (enterprise instanceof PharmaceuticalCompanyEnterprise) {
            PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) enterprise;
            pce.getDrugCatalog().addDrug(d);

        }

        populateDrugTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButton2ActionPerformed
        // TODO add your handling code here:

        PC_FdaWorkRequest pcfwr = new PC_FdaWorkRequest();
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss  MMM/dd/yyyy");
        String reqDate = (dateFormat.format(date));

        int selectedRow = drugjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please choose a drug");
            return;

        }
        Drug d = (Drug) drugjTable.getValueAt(selectedRow, 2);
        pcfwr.setSender(userAccount);
        pcfwr.setSenderCo(enterprise);
        pcfwr.setRequestDate(reqDate);
        pcfwr.setResolveDate(null);
        pcfwr.setStatus("Sent to FDA");
        d.setApprovalStatus("Sent to FDA");
        pcfwr.setDrug(d);

        Organization org = null;
        for (Network n : ecosystem.getcountryNetworkList()) {
            for (StateNetwork sn : n.getStateNetworkList()) {
                for (CityNetwork cn : sn.getCityNetworkList()) {
                    for (Enterprise e : cn.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                            System.out.println(organization);
                            if (organization instanceof FDAMgrOrganization) {

                                org = organization;
                            }
                        }
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkList().add(pcfwr);
            userAccount.getWorkQueue().getWorkList().add(pcfwr);
        }
        populateDrugTable();
        populateReqTable();
    }//GEN-LAST:event_sendjButton2ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField additivesjTextField;
    private javax.swing.JButton backButton2;
    private javax.swing.JTextField compoundsjTextField;
    private javax.swing.JTextField dajTextField1;
    private javax.swing.JTextField dcjTextField;
    private javax.swing.JTable drugjTable;
    private javax.swing.JComboBox drugtypejComboBox;
    private javax.swing.JTextField expdatejTextField;
    private javax.swing.JTextField gnamejTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mednamejTextField1;
    private javax.swing.JTable reqjTable;
    private javax.swing.JButton sendjButton2;
    private javax.swing.JTextField sideeffectsTextField1;
    // End of variables declaration//GEN-END:variables

    private void populateDrugTable() {
        DefaultTableModel model = (DefaultTableModel) drugjTable.getModel();
        model.setRowCount(0);
        PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) enterprise;
        for (Drug d : pce.getDrugCatalog().getDrugList()) {
            Object[] row = new Object[10];
            row[0] = d.getDrugNo();
            row[1] = d.getDrugType();
            row[2] = d;
            row[3] = d.getCompoundName();
            row[4] = d.getAdditives();
            row[5] = d.getDosage();
            row[6] = d.getSide_effects();
            row[7] = d.getExpDate();
            row[8] = d.getApprovalStatus();

            model.addRow(row);
        }
    }

    private void populateReqTable() {
        DefaultTableModel model = (DefaultTableModel) reqjTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkList()) {
            //System.out.println(request);
            if (request instanceof PC_FdaWorkRequest) {
                PC_FdaWorkRequest pcfwr = (PC_FdaWorkRequest) request;
                if (pcfwr.getSenderCo().equals(enterprise)) {
                    Object[] row = new Object[7];
                    row[0] = pcfwr.getDrug();
                    row[1] = pcfwr.getSenderCo();
                    row[2] = pcfwr.getSender();
                    row[3] = pcfwr.getRequestDate();
                    row[4] = pcfwr.getReceiver();
                    row[5] = pcfwr.getDrug().getApprovalStatus();
                    row[6] = pcfwr.getResolveDate();
                    model.addRow(row);

                }
            }
        }
        populateDrugTable();
    }

    private void popDrugType() {
        drugtypejComboBox.removeAllItems();
        for (Drug.DrugType type : Drug.DrugType.values()) {
            drugtypejComboBox.addItem(type);
        }
    }
}
