/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmaCoMgr;

import Business.Enterprise.Enterprise;
import Business.Organization.PharmaceuticalCompanyMgrOrganization;
import Business.Organization.PharmacistOrganization;
import Business.Start.Ecosystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Loukik
 */
public class PharmaCoMgrWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmaCoMgrWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PharmaceuticalCompanyMgrOrganization pharmaceuticalCompanyMgrOrganization;
    private Ecosystem ecosystem;
    private Enterprise enterprise;
    public PharmaCoMgrWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,PharmaceuticalCompanyMgrOrganization organization,Enterprise enterprise,Ecosystem ecosystem) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.pharmaceuticalCompanyMgrOrganization=organization;
        this.ecosystem=ecosystem;
        this.enterprise=enterprise;
        jLabel2.setText(userAccount.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddDrugjButton = new javax.swing.JButton();
        fdafeedbackjButton = new javax.swing.JButton();

        jLabel1.setText("Manager Work Area");

        jLabel2.setText("jLabel2");

        AddDrugjButton.setText("Add New Drug >>");
        AddDrugjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDrugjButtonActionPerformed(evt);
            }
        });

        fdafeedbackjButton.setText("View FDA Feedback>>");
        fdafeedbackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdafeedbackjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fdafeedbackjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(AddDrugjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(AddDrugjButton)
                .addGap(18, 18, 18)
                .addComponent(fdafeedbackjButton)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddDrugjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDrugjButtonActionPerformed
        // TODO add your handling code here:
        AddDrugJPanel panel= new AddDrugJPanel(userProcessContainer,userAccount,pharmaceuticalCompanyMgrOrganization,enterprise,ecosystem);
        userProcessContainer.add("AddDrugJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AddDrugjButtonActionPerformed

    private void fdafeedbackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdafeedbackjButtonActionPerformed
        // TODO add your handling code here:
        ViewFDAFeedbackJPanel panel= new ViewFDAFeedbackJPanel(userProcessContainer,userAccount,pharmaceuticalCompanyMgrOrganization,enterprise,ecosystem);
        userProcessContainer.add("ViewFDAFeedbackJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_fdafeedbackjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDrugjButton;
    private javax.swing.JButton fdafeedbackjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
