/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalDoctor;

import Business.Employee.Doctor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.HospitalDoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Allergy;
import Business.Patient.Demographics;
import Business.Patient.Patient;
import Business.Role.HospitalPatientRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chirag
 */
public class AddPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private HospitalDoctorOrganization hospitalDoctorOrganization;
    private Patient p;
    private Enterprise enterprise;
    private PatientOrganization patientOrganization;

    public AddPatientJPanel(JPanel userProcessContainer, UserAccount userAccount, HospitalDoctorOrganization horg, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.hospitalDoctorOrganization = horg;
        this.enterprise = enterprise;
        //     this.patientOrganization= patientOrganization;
        this.p = new Patient();
        int pid = p.getPid();
        pidjTextField.setText(Integer.toString(pid));
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) allergyjTable1.getModel();
        model.setRowCount(0);
        for (Allergy a : p.getAllergyList().getAllergyList()) {
            Object[] row = new Object[5];
            row[0] = a.getAllergyName();
            row[1] = a.getAllergyDesc();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        patientjTabbedPane = new javax.swing.JTabbedPane();
        pdjPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fnamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnamejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dobjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pidjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ssnjTextField = new javax.swing.JTextField();
        bloodgrpjTextField = new javax.swing.JTextField();
        save1jButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        incompjTextField1 = new javax.swing.JTextField();
        innojTextField2 = new javax.swing.JTextField();
        demographicsjPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        staddjTextField = new javax.swing.JTextField();
        aptnojTextField = new javax.swing.JTextField();
        cityjTextField = new javax.swing.JTextField();
        statejTextField = new javax.swing.JTextField();
        countryjTextField = new javax.swing.JTextField();
        zipjTextField6 = new javax.swing.JTextField();
        save2jButton = new javax.swing.JButton();
        AllergiesjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allergyjTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        allergyjTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descjTextArea = new javax.swing.JTextArea();
        save3jButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        unamejTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        createjButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        backButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Add Patient");

        jLabel2.setText("First name:");

        fnamejTextField.setText("Chirag");
        fnamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamejTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Last name:");

        lnamejTextField.setText("Oswal");

        jLabel4.setText("Date of birth:");

        dobjTextField.setText("08091991");

        jLabel5.setText("Patient ID:");

        jLabel6.setText("Blood Group:");

        jLabel7.setText("SSN:");

        ssnjTextField.setText("5453Asd");

        bloodgrpjTextField.setText("o");

        save1jButton.setText("SAVE");
        save1jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1jButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Insurance company:");

        jLabel19.setText("Insurance No:");

        incompjTextField1.setText("iso");

        innojTextField2.setText("6567ISO8");

        javax.swing.GroupLayout pdjPanel1Layout = new javax.swing.GroupLayout(pdjPanel1);
        pdjPanel1.setLayout(pdjPanel1Layout);
        pdjPanel1Layout.setHorizontalGroup(
            pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pdjPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(fnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pdjPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lnamejTextField))
                    .addGroup(pdjPanel1Layout.createSequentialGroup()
                        .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobjTextField)
                            .addComponent(pidjTextField)))
                    .addGroup(pdjPanel1Layout.createSequentialGroup()
                        .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnjTextField)
                            .addComponent(bloodgrpjTextField))))
                .addGap(18, 18, 18)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(incompjTextField1)
                    .addComponent(innojTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdjPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save1jButton)
                .addGap(125, 125, 125))
        );
        pdjPanel1Layout.setVerticalGroup(
            pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(incompjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(innojTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bloodgrpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pdjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ssnjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(save1jButton)
                .addGap(30, 30, 30))
        );

        patientjTabbedPane.addTab("Patient Details", pdjPanel1);

        jLabel8.setText("Street Address:");

        jLabel9.setText("Apt No:");

        jLabel10.setText("City:");

        jLabel11.setText("State:");

        jLabel12.setText("Country:");

        jLabel13.setText("Zip code:");

        staddjTextField.setText("75 St Alphonsus");

        aptnojTextField.setText("803");

        cityjTextField.setText("Bos");

        statejTextField.setText("MA");

        countryjTextField.setText("USA");

        zipjTextField6.setText("02120");

        save2jButton.setText("SAVE");
        save2jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout demographicsjPanelLayout = new javax.swing.GroupLayout(demographicsjPanel);
        demographicsjPanel.setLayout(demographicsjPanelLayout);
        demographicsjPanelLayout.setHorizontalGroup(
            demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staddjTextField)
                    .addComponent(aptnojTextField)
                    .addComponent(cityjTextField)
                    .addComponent(statejTextField)
                    .addComponent(countryjTextField)
                    .addComponent(zipjTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, demographicsjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save2jButton)
                .addGap(67, 67, 67))
        );
        demographicsjPanelLayout.setVerticalGroup(
            demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demographicsjPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(staddjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(aptnojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(countryjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(demographicsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(zipjTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(save2jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        patientjTabbedPane.addTab("Demographics", demographicsjPanel);

        allergyjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allergy ", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(allergyjTable1);
        if (allergyjTable1.getColumnModel().getColumnCount() > 0) {
            allergyjTable1.getColumnModel().getColumn(0).setResizable(false);
            allergyjTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel14.setText("Allergy:");

        allergyjTextField.setText("w");

        jLabel15.setText("Allergy Description:");

        descjTextArea.setColumns(20);
        descjTextArea.setRows(5);
        descjTextArea.setText("ww");
        jScrollPane2.setViewportView(descjTextArea);

        save3jButton.setText("SAVE");
        save3jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AllergiesjPanelLayout = new javax.swing.GroupLayout(AllergiesjPanel);
        AllergiesjPanel.setLayout(AllergiesjPanelLayout);
        AllergiesjPanelLayout.setHorizontalGroup(
            AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllergiesjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(save3jButton)
                        .addGroup(AllergiesjPanelLayout.createSequentialGroup()
                            .addGroup(AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allergyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        AllergiesjPanelLayout.setVerticalGroup(
            AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllergiesjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(allergyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AllergiesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addComponent(save3jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        patientjTabbedPane.addTab("Allergies", AllergiesjPanel);

        jLabel16.setText("Username:");

        jLabel17.setText("Password:");

        createjButton.setText("Create");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createjButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField))))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(unamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(createjButton)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        patientjTabbedPane.addTab("Account Details", jPanel1);

        backButton2.setText("<<Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientjTabbedPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(backButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(patientjTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:

        String username = unamejTextField.getText();
       char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof PatientOrganization) {
                o.getEmployeeDirectory().createPatient(p);
                Doctor d = (Doctor) userAccount.getEmployee();
                d.getPatientDirectory().addPatient(p);
                Employee e = p;
                UserAccount ua = o.getUserAccountDirectory().createUserAccount(username, password, e, new HospitalPatientRole());
            }

//            for(Employee e1: o.getEmployeeDirectory().getEmployeeList()){
//                System.out.println(e1);
//            }
        }

        System.out.println("Patient added");

    }//GEN-LAST:event_createjButtonActionPerformed

    private void save1jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1jButtonActionPerformed
        // TODO add your handling code here:
        String fname = fnamejTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", fname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter First Name", null, JOptionPane.CANCEL_OPTION);
      return;
       } 
       
       String lname = lnamejTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", lname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Last Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       String iname = incompjTextField1.getText();
       if(Pattern.matches("[a-zA-Z]+", iname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Company Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
        p.setFname(fnamejTextField.getText());
        p.setLname(lnamejTextField.getText());
        p.setSSN(ssnjTextField.getText());
        p.setBloodGroup(bloodgrpjTextField.getText());
        p.setDob(dobjTextField.getText());
        p.setInsurance_company(incompjTextField1.getText());
        p.setInsurance_no(innojTextField2.getText());
        p.setDoctor((Doctor) userAccount.getEmployee());

    }//GEN-LAST:event_save1jButtonActionPerformed

    private void save2jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2jButtonActionPerformed
        // TODO add your handling code here:
        Demographics d = new Demographics();
        
       /* String sname = staddjTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", sname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Street Name", null, JOptionPane.CANCEL_OPTION);
      return;
       } */  
       
       String stname = statejTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", stname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter State Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       String cname = countryjTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", cname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Country Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       String ciname = cityjTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", ciname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter City Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
       
       String aptname = aptnojTextField.getText();
       if(Pattern.matches("[0-9]+", aptname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Apt no", null, JOptionPane.CANCEL_OPTION);
      return;
       }  
       
       String zip = zipjTextField6.getText();
       if(Pattern.matches("[0-9]+", zip)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Zipcode", null, JOptionPane.CANCEL_OPTION);
      return;
       }   
        d.setStname(staddjTextField.getText());
        d.setAptno(aptnojTextField.getText());
        d.setState(statejTextField.getText());
        d.setCountry(countryjTextField.getText());
        d.setZip((Integer.parseInt(zipjTextField6.getText())));
        d.setCity(cityjTextField.getText());
        p.setDemographics(d);

    }//GEN-LAST:event_save2jButtonActionPerformed

    private void save3jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3jButtonActionPerformed
        // TODO add your handling code here:
        Allergy al = new Allergy();
                
                String aname = allergyjTextField.getText();
       if(Pattern.matches("[a-zA-Z]+", aname)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Name", null, JOptionPane.CANCEL_OPTION);
      return;
       }   

        al.setAllergyName(allergyjTextField.getText());
        al.setAllergyDesc(descjTextArea.getText());
        p.getAllergyList().addAllergy(al);
        populateTable();

    }//GEN-LAST:event_save3jButtonActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void fnamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamejTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AllergiesjPanel;
    private javax.swing.JTable allergyjTable1;
    private javax.swing.JTextField allergyjTextField;
    private javax.swing.JTextField aptnojTextField;
    private javax.swing.JButton backButton2;
    private javax.swing.JTextField bloodgrpjTextField;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JTextField countryjTextField;
    private javax.swing.JButton createjButton;
    private javax.swing.JPanel demographicsjPanel;
    private javax.swing.JTextArea descjTextArea;
    private javax.swing.JTextField dobjTextField;
    private javax.swing.JTextField fnamejTextField;
    private javax.swing.JTextField incompjTextField1;
    private javax.swing.JTextField innojTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lnamejTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTabbedPane patientjTabbedPane;
    private javax.swing.JPanel pdjPanel1;
    private javax.swing.JTextField pidjTextField;
    private javax.swing.JButton save1jButton;
    private javax.swing.JButton save2jButton;
    private javax.swing.JButton save3jButton;
    private javax.swing.JTextField ssnjTextField;
    private javax.swing.JTextField staddjTextField;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JTextField unamejTextField;
    private javax.swing.JTextField zipjTextField6;
    // End of variables declaration//GEN-END:variables

}
