/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalDoctor;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDA;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.CityNetwork;
import Business.Network.Network;
import Business.Network.StateNetwork;
import Business.Organization.HospitalDoctorOrganization;
import Business.Organization.HospitalLabOrganization;
import Business.Organization.HospitalNurseOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.Patient.Allergy;
import Business.Patient.Encounter;
import Business.Patient.Medication;
import Business.Patient.Patient;
import Business.Start.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.Dr_LabWorkRequest;
import Business.WorkRequest.Dr_PharmacyWorkRequest;
import Business.WorkRequest.NurseWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chirag
 */
public class TreatpatientJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form TreatpatientJPanel
     */
    JPanel userProcessContainer;
    Patient patient;
    Encounter e;
    UserAccount userAccount;
    HospitalDoctorOrganization hospitalDoctorOrganization;
    Enterprise enterprise;
    private Ecosystem ecosystem;

    public TreatpatientJPanel1(JPanel userProcessContainer, UserAccount userAccount, HospitalDoctorOrganization hospitalDoctorOrganization, Enterprise enterprise, Patient patient, Ecosystem ecosystem) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.enterprise = enterprise;
        this.hospitalDoctorOrganization = hospitalDoctorOrganization;
        this.ecosystem = ecosystem;
        namejTextField1.setText(patient.getFname() + " " + patient.getLname());
        e = new Encounter();
        timejTextField1.setText(e.getTimeStamp());
        treatedbyjTextField1.setText(userAccount.getUserName());

        //prescription
        e.getPrescription().setTimeOfIssue(e.getTimeStamp());
        e.getPrescription().setSignedBy(userAccount.getEmployee().getFname() + " " + userAccount.getEmployee().getLname());
        e.getPrescription().setDoctor(userAccount.getEmployee().getFname() + " " + userAccount.getEmployee().getLname());
        e.getPrescription().setPatient(patient.getFname() + " " + patient.getLname());

        populateNurseTable();
        populateLabTable();
        populateAllergyTable();
        populatemedicineComboBox();
        populatepharmacyCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        timejTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        treatedbyjTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        nursewrjTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        messagejTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        labjTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        labmsgjTextField = new javax.swing.JTextField();
        sendtoLabjButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complajTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sympjTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnosisjTextArea3 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        treatmentjTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        digitalsignjTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bpjTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hrjTextField1 = new javax.swing.JTextField();
        wtjTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pulsejTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        vstakenbyjTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        testresultjTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        labtestdonebyjTextField = new javax.swing.JTextField();
        medicinejComboBox1 = new javax.swing.JComboBox();
        jScrollPane9 = new javax.swing.JScrollPane();
        prescriptionjTable1 = new javax.swing.JTable();
        refilljTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pharmacyjComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        allergyjTable = new javax.swing.JTable();
        backButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Treatment");

        jLabel2.setText("Patient Name:");

        jLabel3.setText("Time of visit:");

        jLabel9.setText("Name of doctor:");

        nursewrjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Message", "Status", "Patient Name"
            }
        ));
        jScrollPane6.setViewportView(nursewrjTable);

        jButton3.setText("Send Request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Message:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(messagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(messagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(335, 335, 335))
        );

        jTabbedPane1.addTab("Refer to Nurse", jPanel1);

        labjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Message", "Status", "Patient"
            }
        ));
        jScrollPane7.setViewportView(labjTable);

        jLabel19.setText("Message:");

        sendtoLabjButton.setText("Send Lab request");
        sendtoLabjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtoLabjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labmsgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sendtoLabjButton))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(labmsgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(sendtoLabjButton)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Refer to Lab", jPanel3);

        jLabel4.setText("Reason/Complaint:");

        complajTextArea1.setColumns(20);
        complajTextArea1.setRows(5);
        jScrollPane1.setViewportView(complajTextArea1);

        jLabel7.setText("Symptoms:");

        sympjTextArea2.setColumns(20);
        sympjTextArea2.setRows(5);
        jScrollPane2.setViewportView(sympjTextArea2);

        jLabel5.setText("Diagnosis:");

        diagnosisjTextArea3.setColumns(20);
        diagnosisjTextArea3.setRows(5);
        jScrollPane3.setViewportView(diagnosisjTextArea3);

        jLabel8.setText("Treatment:");

        treatmentjTextArea.setColumns(20);
        treatmentjTextArea.setRows(5);
        jScrollPane5.setViewportView(treatmentjTextArea);

        jLabel10.setText("Digital Sign:");

        jLabel12.setText("Blood Pressure:");

        jLabel13.setText("Heart rate:");

        jLabel14.setText("Weight:");

        jLabel15.setText("Pulse Rate:");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Vital Signs taken by:");

        jLabel17.setText("Lab Test Result:");

        jLabel18.setText("Lab Test Done by:");

        medicinejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prescriptionjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Medicine Name", "Generic Name", "Refills"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(prescriptionjTable1);

        jLabel20.setText("Prescription:");

        jLabel21.setText("Refill:");

        jLabel22.setText("Medicine Name:");

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pharmacyjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Pharmacy Name");

        jButton4.setText("Forward to Pharmacy>>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(testresultjTextField))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hrjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wtjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pulsejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(vstakenbyjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labtestdonebyjTextField))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel7)))
                                .addGap(7, 7, 7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(medicinejComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel10))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(digitalsignjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(119, 119, 119)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pharmacyjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(refilljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(hrjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wtjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(pulsejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(vstakenbyjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(testresultjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(labtestdonebyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medicinejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(refilljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(digitalsignjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pharmacyjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create Report", jPanel4);

        allergyjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allergy Name", "Allergy Type"
            }
        ));
        jScrollPane8.setViewportView(allergyjTable);

        backButton3.setText("<<Back");
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(90, 90, 90)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(timejTextField1)
                    .addComponent(treatedbyjTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton3)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(timejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(treatedbyjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton3))
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String bp = bpjTextField.getText();
       if(Pattern.matches("[0-9]+", bp)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Blood pressure value", null, JOptionPane.CANCEL_OPTION);
      return;
       } 
       
        String hr = hrjTextField1.getText();
       if(Pattern.matches("[0-9]+", hr)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Heart rate", null, JOptionPane.CANCEL_OPTION);
      return;
       } 
       
       String wtj = wtjTextField.getText();
       if(Pattern.matches("[0-9]+", wtj)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Weight", null, JOptionPane.CANCEL_OPTION);
      return;
       }
       
       String pulse = pulsejTextField.getText();
       if(Pattern.matches("[0-9]+", pulse)) 
       {}
       else
       {
      JOptionPane.showConfirmDialog(null, "Please enter Pulse rate", null, JOptionPane.CANCEL_OPTION);
      return;
       }
       
       
        e.setComplaint(complajTextArea1.getText());
        e.setDiagnosis(diagnosisjTextArea3.getText());
        // e.setMedication(medicationjTextArea4.getText());
        e.setSymptoms(sympjTextArea2.getText());
        e.setTreatment(treatmentjTextArea.getText());
        e.setTreatedby(userAccount.getUserName());
        e.setDigitalsign(digitalsignjTextField1.getText());
        //vitals
        e.getVitalSigns().setBloodPressure(Double.parseDouble(bpjTextField.getText()));
        e.getVitalSigns().setHeartRate(Double.parseDouble(hrjTextField1.getText()));
        e.getVitalSigns().setWeight(Double.parseDouble(wtjTextField.getText()));
        e.getVitalSigns().setPulseRate(Double.parseDouble(pulsejTextField.getText()));
        //lab report
        e.setLabreport(testresultjTextField.getText());
        e.setNurse(vstakenbyjTextField1.getText());
        e.setLabasst(labtestdonebyjTextField.getText());
        e.setHospital(enterprise);

        //adding to encounter history
        patient.getEncounterHistory().addEncounter(e);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NurseWorkRequest nurseWorkRequest = new NurseWorkRequest();
        nurseWorkRequest.setSender(userAccount);
        nurseWorkRequest.setMessage(messagejTextField.getText());
        nurseWorkRequest.setPatient(patient);
        nurseWorkRequest.setStatus("Request Sent");
        nurseWorkRequest.setEncounter(e);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {

            if (organization instanceof HospitalNurseOrganization) {

                org = organization;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkList().add(nurseWorkRequest);
            userAccount.getWorkQueue().getWorkList().add(nurseWorkRequest);
        }
        populateNurseTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sendtoLabjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtoLabjButtonActionPerformed
        // TODO add your handling code here:
        Dr_LabWorkRequest dr_LabWorkRequest = new Dr_LabWorkRequest();
        dr_LabWorkRequest.setSender(userAccount);
        dr_LabWorkRequest.setMessage(labmsgjTextField.getText());
        dr_LabWorkRequest.setPatient(patient);
        dr_LabWorkRequest.setStatus("Request Sent");
        dr_LabWorkRequest.setEncounter(e);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {

            if (organization instanceof HospitalLabOrganization) {

                org = organization;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkList().add(dr_LabWorkRequest);
            userAccount.getWorkQueue().getWorkList().add(dr_LabWorkRequest);
        }
        populateLabTable();
    }//GEN-LAST:event_sendtoLabjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Medication m = new Medication();
        m.setDrug((Drug) medicinejComboBox1.getSelectedItem());
        m.setRefill(Integer.parseInt(refilljTextField1.getText()));
        e.getPrescription().getMedicationList().add(m);
        populatePrescription();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Dr_PharmacyWorkRequest dpwr = new Dr_PharmacyWorkRequest();
        dpwr.setEncounter(e);
        dpwr.setPrescription(e.getPrescription());
        dpwr.setSender(userAccount);
        dpwr.setMessage("Provide mentioned drugs");
       // dpwr.setReceiver((UserAccount) pharmacyjComboBox1.getSelectedItem());
        dpwr.setStatus("Prescription sent");

        Enterprise ent1= (Enterprise) pharmacyjComboBox1.getSelectedItem();
        for(Organization org:ent1.getOrganizationDirectory().getOrganizationList())
        {
        if(org instanceof PharmacistOrganization)
        {
        org.getWorkQueue().getWorkList().add(dpwr);
        userAccount.getWorkQueue().getWorkList().add(dpwr);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allergyjTable;
    private javax.swing.JButton backButton3;
    private javax.swing.JTextField bpjTextField;
    private javax.swing.JTextArea complajTextArea1;
    private javax.swing.JTextArea diagnosisjTextArea3;
    private javax.swing.JTextField digitalsignjTextField1;
    private javax.swing.JTextField hrjTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable labjTable;
    private javax.swing.JTextField labmsgjTextField;
    private javax.swing.JTextField labtestdonebyjTextField;
    private javax.swing.JComboBox medicinejComboBox1;
    private javax.swing.JTextField messagejTextField;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JTable nursewrjTable;
    private javax.swing.JComboBox pharmacyjComboBox1;
    private javax.swing.JTable prescriptionjTable1;
    private javax.swing.JTextField pulsejTextField;
    private javax.swing.JTextField refilljTextField1;
    private javax.swing.JButton sendtoLabjButton;
    private javax.swing.JTextArea sympjTextArea2;
    private javax.swing.JTextField testresultjTextField;
    private javax.swing.JTextField timejTextField1;
    private javax.swing.JTextField treatedbyjTextField1;
    private javax.swing.JTextArea treatmentjTextArea;
    private javax.swing.JTextField vstakenbyjTextField1;
    private javax.swing.JTextField wtjTextField;
    // End of variables declaration//GEN-END:variables

    private void populateNurseTable() {
        DefaultTableModel model = (DefaultTableModel) nursewrjTable.getModel();
        //set the orgainzation's work queue
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkList()) {
            //System.out.println(request);
            if (request instanceof NurseWorkRequest) {
                NurseWorkRequest nwr = (NurseWorkRequest) request;
                if (nwr.getPatient().equals(patient)) {
                    Object[] row = new Object[5];
                    row[0] = request.getSender();
                    row[1] = request.getReceiver();
                    row[2] = request.getMessage();
                    row[3] = request.getStatus();

                    row[4] = nwr.getPatient();
                    model.addRow(row);

                    bpjTextField.setText(String.valueOf(request.getEncounter().getVitalSigns().getBloodPressure()));
                    hrjTextField1.setText(String.valueOf(request.getEncounter().getVitalSigns().getHeartRate()));
                    wtjTextField.setText(String.valueOf(request.getEncounter().getVitalSigns().getWeight()));
                    pulsejTextField.setText(String.valueOf(request.getEncounter().getVitalSigns().getPulseRate()));
                    if (nwr.getReceiver() != null) {
                        vstakenbyjTextField1.setText(nwr.getReceiver().getUserName());
                    }

                }
            }
        }
    }

    private void populateLabTable() {
        DefaultTableModel model = (DefaultTableModel) labjTable.getModel();
        //set the orgainzation's work queue
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkList()) {
            //System.out.println(request);
            if (request instanceof Dr_LabWorkRequest) {
                Dr_LabWorkRequest dlwr = (Dr_LabWorkRequest) request;
                if (dlwr.getPatient().equals(patient)) {
                    Object[] row = new Object[5];
                    row[0] = request.getSender();
                    row[1] = request.getReceiver();
                    row[2] = request.getMessage();
                    row[3] = request.getStatus();
                    row[4] = dlwr.getPatient();
                    model.addRow(row);
                    testresultjTextField.setText(dlwr.getTestResult());
                    if (dlwr.getReceiver() != null) {
                        labtestdonebyjTextField.setText(dlwr.getReceiver().getUserName());
                    }
                }
            }
        }
    }

    private void populateAllergyTable() {
        DefaultTableModel model = (DefaultTableModel) allergyjTable.getModel();
        //set the orgainzation's work queue
        model.setRowCount(0);
        for (Allergy a : patient.getAllergyList().getAllergyList()) {

            Object[] row = new Object[2];
            row[0] = a.getAllergyName();
            row[1] = a.getAllergyDesc();
            model.addRow(row);

        }
    }

    private void populatemedicineComboBox() {
        medicinejComboBox1.removeAllItems();
        FDA fda;
        for (Network n : ecosystem.getcountryNetworkList()) {
            for (StateNetwork sn : n.getStateNetworkList()) {
                for (CityNetwork cn : sn.getCityNetworkList()) {
                    for (Enterprise e : cn.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e instanceof FDA) {
                            fda = (FDA) e;
                            for (Drug d : fda.getDrugCatalog().getDrugList()) {
                                medicinejComboBox1.addItem(d);

                            }

                        }
                    }
                }
            }
        }
    }

    private void populatePrescription() {
        DefaultTableModel model = (DefaultTableModel) prescriptionjTable1.getModel();
        //set the orgainzation's work queue
        model.setRowCount(0);
        for (Medication m : e.getPrescription().getMedicationList()) {
            Object[] row = new Object[4];
            row[0] = m.getDrug().getMedicineName();
            row[1] = m.getDrug().getGenericName();
            row[2] = m.getRefill();
            model.addRow(row);

        }
    }

    private void populatepharmacyCombo() {
        pharmacyjComboBox1.removeAllItems();
        for (Network n : ecosystem.getcountryNetworkList()) {
            for (StateNetwork sn : n.getStateNetworkList()) {
                for (CityNetwork cn : sn.getCityNetworkList()) {
                    for (Enterprise e : cn.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e instanceof PharmacyEnterprise) {
                            pharmacyjComboBox1.addItem(e);
                        }
                    }
                }

            }
        }

    }
}
