/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FDAManager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.FDA;
import Business.Organization.FDAMgrOrganization;
import Business.Start.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.PC_FdaWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chirag
 */
public class DrugApprovalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugApprovalJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private FDAMgrOrganization fDAMgrOrganization;
    private Ecosystem ecosystem;
    private Enterprise enterprise;
    private FDA fdaEnterprise;

    public DrugApprovalJPanel(JPanel userProcessContainer, UserAccount userAccount, FDAMgrOrganization organization, Enterprise e, Ecosystem ecosystem) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.fDAMgrOrganization = organization;
        this.ecosystem = ecosystem;
        this.enterprise = e;
        this.fdaEnterprise = (FDA) e;
        populateReqTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        reqjTable = new javax.swing.JTable();
        appdrugjButton = new javax.swing.JButton();
        rejdrugjButton2 = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();

        reqjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Drug Name", "Drug Type", "Sender Co", "Sender", "Time Sent", "Approved/Rejected By", "Status", "Time Resolved"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reqjTable);

        appdrugjButton.setText("Approve Drug");
        appdrugjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appdrugjButtonActionPerformed(evt);
            }
        });

        rejdrugjButton2.setText("Reject Drug");
        rejdrugjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejdrugjButton2ActionPerformed(evt);
            }
        });

        backButton2.setText("<<Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(appdrugjButton)
                .addGap(55, 55, 55)
                .addComponent(rejdrugjButton2)
                .addGap(18, 18, 18)
                .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appdrugjButton)
                    .addComponent(rejdrugjButton2)
                    .addComponent(backButton2))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appdrugjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appdrugjButtonActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss  MMM/dd/yyyy");
        String resDate = (dateFormat.format(date));
        int selectedRow = reqjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select A Drug!!!");
            return;
        }

        WorkRequest request = (WorkRequest) reqjTable.getValueAt(selectedRow, 0);
        if (request instanceof PC_FdaWorkRequest) {
            PC_FdaWorkRequest pcfwr = (PC_FdaWorkRequest) request;
            pcfwr.setReceiver(userAccount);
            pcfwr.setResolveDate(resDate);
            //setting attributes of the drug
            pcfwr.getDrug().setApprovalStatus("Approved");
            pcfwr.getDrug().setApprovedOn(resDate);
            //add drug to fda approved list
            fdaEnterprise.getDrugCatalog().getDrugList().add(pcfwr.getDrug());

            populateReqTable();
    }//GEN-LAST:event_appdrugjButtonActionPerformed
    }
    private void rejdrugjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejdrugjButton2ActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss  MMM/dd/yyyy");
        String resDate = (dateFormat.format(date));
        int selectedRow = reqjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select A Drug!!!");
            return;
        }

        WorkRequest request = (WorkRequest) reqjTable.getValueAt(selectedRow, 0);
        PC_FdaWorkRequest pcfwr = (PC_FdaWorkRequest) request;
        pcfwr.setReceiver(userAccount);
        pcfwr.setResolveDate(resDate);
        pcfwr.getDrug().setApprovalStatus("Rejected");
        populateReqTable();
    }//GEN-LAST:event_rejdrugjButton2ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appdrugjButton;
    private javax.swing.JButton backButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rejdrugjButton2;
    private javax.swing.JTable reqjTable;
    // End of variables declaration//GEN-END:variables

    private void populateReqTable() {
        DefaultTableModel model = (DefaultTableModel) reqjTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : fDAMgrOrganization.getWorkQueue().getWorkList()) {
            if (request instanceof PC_FdaWorkRequest) {
                PC_FdaWorkRequest pcfwr = (PC_FdaWorkRequest) request;
                Object[] row = new Object[9];
                row[0] = pcfwr;
                row[1] = pcfwr.getDrug().getDrugType();
                row[2] = pcfwr.getSenderCo();
                row[3] = pcfwr.getSender().getEmployee();
                row[4] = pcfwr.getRequestDate();
                row[5] = request.getReceiver() == null ? null : request.getReceiver().getEmployee();
                row[6] = pcfwr.getDrug().getApprovalStatus();
                row[7] = request.getResolveDate() == null ? null : request.getResolveDate();
                model.addRow(row);
            }
        }
    }
}
