/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FDAManager;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDA;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.CityNetwork;
import Business.Network.Network;
import Business.Network.StateNetwork;
import Business.Organization.FDAMgrOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Start.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FDA_PatWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chirag
 */
public class IssueWarningJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IssueWarningJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private FDAMgrOrganization fDAMgrOrganization;
    private Ecosystem ecosystem;
    private Enterprise enterprise;
    private FDA fdaEnterprise;

    public IssueWarningJPanel(JPanel userProcessContainer, UserAccount userAccount, FDAMgrOrganization organization, Enterprise e, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.fDAMgrOrganization = organization;
        this.ecosystem = ecosystem;
        this.enterprise = e;
        if (enterprise instanceof FDA) {
            fdaEnterprise = (FDA) enterprise;
        }
        populateCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        drugjComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sendwarningjButton1 = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();

        jLabel1.setText("Issue warning to patients");

        drugjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Drug name: ");

        jLabel3.setText("Message:");

        sendwarningjButton1.setText("Send Warning");
        sendwarningjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendwarningjButton1ActionPerformed(evt);
            }
        });

        backButton2.setText("<<Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendwarningjButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton2)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(sendwarningjButton1)
                .addGap(18, 18, 18)
                .addComponent(backButton2)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void sendwarningjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendwarningjButton1ActionPerformed
        // TODO add your handling code here:

        FDA_PatWorkRequest fdapwr = new FDA_PatWorkRequest();
        fdapwr.setDrug((Drug) drugjComboBox1.getSelectedItem());
        fdapwr.setMessage(jTextField1.getText());
        fdapwr.setSender(userAccount);

        for (Network n : ecosystem.getcountryNetworkList()) {
            for (StateNetwork sn : n.getStateNetworkList()) {
                for (CityNetwork cn : sn.getCityNetworkList()) {
                    for (Enterprise e : cn.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e instanceof HospitalEnterprise) {
                            HospitalEnterprise he = (HospitalEnterprise) e;

                            for (Organization o : he.getOrganizationDirectory().getOrganizationList()) {
                                if (o instanceof PatientOrganization) {
                                    o.getWorkQueue().getWorkList().add(fdapwr);
                                    userAccount.getWorkQueue().getWorkList().add(fdapwr);
                                }

                            }

                        }
                    }
                }
            }

        }


    }//GEN-LAST:event_sendwarningjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton2;
    private javax.swing.JComboBox drugjComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton sendwarningjButton1;
    // End of variables declaration//GEN-END:variables

    private void populateCombobox() {
        drugjComboBox1.removeAllItems();
        for (Drug drug : fdaEnterprise.getDrugCatalog().getDrugList()) {
            drugjComboBox1.addItem(drug);
        }

    }
}
