/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FDAManager;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDA;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Network.CityNetwork;
import Business.Network.Network;
import Business.Network.StateNetwork;
import Business.Organization.FDAMgrOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmaceuticalCompanyMgrOrganization;
import Business.Start.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FDA_PCWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chirag
 */
public class SendPharmaCoFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendPharmaCoFeedbackJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private FDAMgrOrganization fDAMgrOrganization;
    private Ecosystem ecosystem;
    private FDA fdaEnterprise;

    public SendPharmaCoFeedbackJPanel(JPanel userProcessContainer, UserAccount userAccount, FDAMgrOrganization organization, Enterprise e, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.fDAMgrOrganization = organization;
        this.ecosystem = ecosystem;
        if (e instanceof FDA) {
            fdaEnterprise = (FDA) e;

        }
        populateCombobox();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagejTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        drugjComboBox1 = new javax.swing.JComboBox();
        sendjButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        feedbacktablejTable1 = new javax.swing.JTable();
        backButton2 = new javax.swing.JButton();

        jLabel1.setText("Send Feedback to Pharmaceutical Company");

        jLabel2.setText("Message:");

        messagejTextArea1.setColumns(20);
        messagejTextArea1.setRows(5);
        jScrollPane1.setViewportView(messagejTextArea1);

        jLabel3.setText("Drug Name:");

        drugjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sendjButton1.setText("Send Feedback");
        sendjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButton1ActionPerformed(evt);
            }
        });

        feedbacktablejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Drug Name", "Drug ID", "Reason", "Sent At", "Receiver", "Received At", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(feedbacktablejTable1);

        backButton2.setText("<<Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(drugjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(sendjButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drugjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendjButton1)
                        .addGap(67, 67, 67)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(backButton2)
                .addContainerGap(337, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButton1ActionPerformed
        // TODO add your handling code here:

        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss  MMM/dd/yyyy");
        String reqDate = (dateFormat.format(date));
        FDA_PCWorkRequest fdapcwr = new FDA_PCWorkRequest();
        fdapcwr.setDrug((Drug) drugjComboBox1.getSelectedItem());
        fdapcwr.setMessage(messagejTextArea1.getText());
        fdapcwr.setSender(userAccount);
        fdapcwr.setRequestDate(reqDate);
        fdapcwr.setStatus("Request sent");

        for (Network n : ecosystem.getcountryNetworkList()) {
            for (StateNetwork sn : n.getStateNetworkList()) {
                for (CityNetwork cn : sn.getCityNetworkList()) {
                    for (Enterprise e : cn.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e instanceof PharmaceuticalCompanyEnterprise) {
                            PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) e;

                            if (pce.getName().equals(fdapcwr.getDrug().getManufacturer())) {
                                for (Organization org : pce.getOrganizationDirectory().getOrganizationList()) {
                                    if (org instanceof PharmaceuticalCompanyMgrOrganization) {
                                        org.getWorkQueue().getWorkList().add(fdapcwr);
                                        userAccount.getWorkQueue().getWorkList().add(fdapcwr);
                                    }
                                }
                            }

                        }
                    }
                }
            }

        }
        populateTable();
    }//GEN-LAST:event_sendjButton1ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton2;
    private javax.swing.JComboBox drugjComboBox1;
    private javax.swing.JTable feedbacktablejTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messagejTextArea1;
    private javax.swing.JButton sendjButton1;
    // End of variables declaration//GEN-END:variables

    private void populateCombobox() {
        drugjComboBox1.removeAllItems();
        for (Drug drug : fdaEnterprise.getDrugCatalog().getDrugList()) {
            drugjComboBox1.addItem(drug);
        }

    }

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) feedbacktablejTable1.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : userAccount.getWorkQueue().getWorkList()) {
            if (wr instanceof FDA_PCWorkRequest) {
                FDA_PCWorkRequest request = (FDA_PCWorkRequest) wr;
                Object[] row = new Object[10];
                row[0] = request.getDrug();
                row[1] = request.getDrug().getDrugNo();
                row[2] = request.getMessage();
                row[3] = request.getRequestDate();
                row[4] = request.getReceiver();
                row[5] = request.getResolveDate();
                row[6] = request.getStatus();

                model.addRow(row);
            }
        }
    }

}
