/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdmin;

import Business.Enterprise.Enterprise;
import Business.Network.CityNetwork;
import Business.Network.Network;
import Business.Network.StateNetwork;
import Business.Start.Ecosystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chirag
 */
public class AddFDAOfficeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddHospitalJPanel
     */
     JPanel userProcessContainer;
    Ecosystem ecosystem; 
    public AddFDAOfficeJPanel( JPanel userProcessContainer,Ecosystem ecosystem ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        nwjComboBox1.removeAllItems();
        populateComboBox();
        populateTable();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nwjComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        FDAOfficenamejTextField1 = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FDAjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        statejComboBox1 = new javax.swing.JComboBox();
        cityjComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Add new FDA Nodal Office");

        nwjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nwjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwjComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("FDA Office Name:");

        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        backButton2.setText("<<Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        FDAjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FDA Office Name", "Country Name", "State Name", "City Name", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FDAjTable);
        if (FDAjTable.getColumnModel().getColumnCount() > 0) {
            FDAjTable.getColumnModel().getColumn(0).setResizable(false);
            FDAjTable.getColumnModel().getColumn(1).setResizable(false);
            FDAjTable.getColumnModel().getColumn(2).setResizable(false);
            FDAjTable.getColumnModel().getColumn(3).setResizable(false);
            FDAjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("Country Network:");

        jLabel4.setText("State Network:");

        jLabel5.setText("City Network:");

        statejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statejComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statejComboBox1ActionPerformed(evt);
            }
        });

        cityjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(backButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FDAOfficenamejTextField1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nwjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(statejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cityjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nwjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(statejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cityjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FDAOfficenamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton2)
                    .addComponent(addjButton))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        
         CityNetwork cn = (CityNetwork) cityjComboBox.getSelectedItem();

        if (cn == null) {
            JOptionPane.showMessageDialog(null, "Invalid input");
            return;
        }
        String name = FDAOfficenamejTextField1.getText();
        cn.getEnterpriseDirectory().createAndAddEnterprise(name, Enterprise.EnterpriseType.FDA);
        populateTable();
        
        
        
    }//GEN-LAST:event_addjButtonActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void nwjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwjComboBox1ActionPerformed
        // TODO add your handling code here:
         Network n = (Network) nwjComboBox1.getSelectedItem();
        populateStateComboBox(n);
    }//GEN-LAST:event_nwjComboBox1ActionPerformed

    private void statejComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statejComboBox1ActionPerformed
        // TODO add your handling code here:
        StateNetwork sn = (StateNetwork) statejComboBox1.getSelectedItem();
        populateCityComboBox(sn);
    }//GEN-LAST:event_statejComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FDAOfficenamejTextField1;
    private javax.swing.JTable FDAjTable;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backButton2;
    private javax.swing.JComboBox cityjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox nwjComboBox1;
    private javax.swing.JComboBox statejComboBox1;
    // End of variables declaration//GEN-END:variables

     private void populateComboBox() {
        nwjComboBox1.removeAllItems();
        for (Network n : ecosystem.getcountryNetworkList()) {
            nwjComboBox1.addItem(n);

        }

    }

    private void populateStateComboBox(Network n) {
       if(n!=null){
           statejComboBox1.removeAllItems();
        for (StateNetwork sn : n.getStateNetworkList()) {
            statejComboBox1.addItem(sn);
        }
       }
    }

    private void populateCityComboBox(StateNetwork sn) {
        if(sn!=null){
            cityjComboBox.removeAllItems();
        for (CityNetwork cn : sn.getCityNetworkList()) {
            cityjComboBox.addItem(cn);
        }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) FDAjTable.getModel();
        model.setRowCount(0);
        for (Network n : ecosystem.getcountryNetworkList()) {
            for (StateNetwork sn : n.getStateNetworkList()) {
                for (CityNetwork cn : sn.getCityNetworkList()) {

                    for (Enterprise enterprise : cn.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise.getEnterpriseType().getValue() == "FDA") 
                        {
                            Object[] row = new Object[5];
                            row[0] = enterprise.getName();
                            row[1] = n.getCountryname();
                            row[2] = sn.getStatename();
                            row[3] = cn.getCityname();
                            row[4] = enterprise.getEnterpriseType();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }
}
